### ISSUE TITLE
Proposal: Unified unit format

### ISSUE THREAD

**Issue by robertvanhoesel** [aoe4world/data#1]
We'll need to create a format that is both easy to consume as more complete in terms of unit variations. 

Here's an early draft, open for feedback.
- instead of `attack` and `armor` with calculated totals, they're now an array of weapons/types with their own speed, etc
- Option to add bonus damage on weapons
- Clearer class definition which can be used in modifiers, technologies etc.

Some thoughts:
- I think variations in itself should contain all the data you would need to describe the unit, the unifier merely groups them.
- Need to verify how these map from game files – should be reasonable easy to map
- Should we include available upgrades to each variation? I.e. 
   	`upgrades: [{ to: 'man-at-arms-4', label: "Elite Men-at-Arms", costs: {...}]`
   - I would consider upgrades to exist independently from units, however there's also a strong connection between them.

```js
const unit =
    // Essentially a unit always groups variations and does not include a lot of info
    {
        name: "Man-at-arms",
        id: "men-at-arms",
        civs: ["en", "hr"],
        class: ["heavy-infantry"], // basically the grouping can summarize/repeat what the variations hold
        age: 2, // Or expressed as an array in which the unit is available [2, 3, 4]
        variations: [
            // i.e. an upgraded version or economic variation produced in a specific building,
            // or stronger such as siege
            // Can differ in costs, stats etc.
            // Can be available to a subset of civs.
            {
                name: "Veteran Man-at-arms",
                id: "men-at-arms-3",
                civs: ["en", "hr"],
                class: ["heavy-infantry"],
                age: 4,
                costs: { ...{} },
                hitpoints: 123,
                weapons: [
                    {
                        type: "melee",
                        damage: 8,
                        speed: 1.1,
                        modifiers: [
                            {
                                class: ["light-ranged"],
                                damage: ["increase", 2],
                            },
                            {
                                class: ["heavy-mounted"],
                                damage: ["multiply", 1.1],
                            },
                        ],
                    },
                    {
                        type: "fire",
                        damage: 3,
                        speed: 0.5,
                    },
                ],
                armor: [
                    {
                        type: "melee",
                        value: 2,
                    },
                ],
                producedBy: ["..."],
            },
        ],
    };
```

**Comment by keiras** [comment]
> Clearer class definition which can be used in modifiers, technologies etc.

I would suggest to split the class labels in a more atomic way. In the MAA example, that would be ["heavy", "infantry"] or possibly even ["heavy", "infantry", "melee", "man-at-arms"]. The attack modifiers  and upgrades tend to be all over the place regarding the possible tag combinations. Using this general approach, it would be possible to pair up the unit data with upgrades and other units more easily. 

Modifier could be serialized as `class: ["light", "ranged"]` having the logical AND meaning. Logical OR (if needed) could be serialized by creating additional item in the modifiers array.

> I think variations in itself should contain all the data you would need to describe the unit, the unifier merely groups them.
>Should we include available upgrades to each variation? I.e. upgrades: [{ to: 'man-at-arms-4', label: "Elite Men-at-Arms", costs: {...}]

I am a bit puzzled on what the optimal solution would be. In the proposed format, there will be issues with units being introduced in different ages. England has MAA since age 1, HRE has them since age 2, 5 more civs have them since age 3, Chinese have different unit in this role.
I think it would make sense to provide either a generic statement about the unit type in the unifier, that is `civs: ["en", "hr", "ab", "de", "ru", "mo", "fr"]` with no age information, or instead provide an information about the introduction age for individual civs e.g. `"introduced-in": {"en":1, "hr":2, "ab":3, "de":3, "ru":3, "mo":3, "fr":3, "ch":null}`

Providing all the variations would lead to rather complex and hard to read data files. It might be better to roll back to the previous approach with having a single file per variation and keep some sort of textual reference in other relevant data objects.

**Comment by robertvanhoesel** [comment]
Thanks for the feedback!

> I would suggest to split the class labels in a more atomic way. In the MAA example, that would be ["heavy", "infantry"] or possibly even ["heavy", "infantry", "melee", "man-at-arms"].

I like the normalized unit name here a lot, good way to join Mangudai and Horse Archers, palace guards and maa, lancers and knights etc together.

> Modifier could be serialized as class: ["light", "ranged"] having the logical AND meaning. Logical OR (if needed) could be serialized by creating additional item in the modifiers array.

With something like
```
horse archers: light, cavalry, ranged
knight: heavy, cavalry, melee
bombard: siege, gunpowder
springald: siege
cannoneer: infantry, ranged, gunpowder
archer: light, infantry, ranged
keep: building, defense, stone,
gate: building, defense, stone
```
a modifier like `Increase the ranged damage of all non-siege units and buildings by +%1%.` or `Increase the damage of ranged units and buildings by +%1%%%. Does not apply to gunpowder units.` would be hard to target with simple AND statements. So you would either need very exhaustive lists (more work) or exclusive statements (this does not feel user friendly). I guess adding things like 'wall', 'non-gunpowder' could work with this.

> I think it would make sense to provide either a generic statement about the unit type in the unifier, that is civs: ["en", "hr", "ab", "de", "ru", "mo", "fr"] with no age information, or instead provide an information about the introduction age for individual civs e.g. "introduced-in": {"en":1, "hr":2, "ab":3, "de":3, "ru":3, "mo":3, "fr":3, "ch":null}

Hmm valid point, it would indeed be confusing to use it in the grouping.

> Providing all the variations would lead to rather complex and hard to read data files. It might be better to roll back to the previous approach with having a single file per variation and keep some sort of textual reference in other relevant data objects.

So what I think would be good is to have per unit per variation source files (like right now), with some of the suggested changes. We already compile and `all.json` and `hre.json` etc so joining in variations that make sense could work well for those that want to consume it in that way.

**Comment by robertvanhoesel** [comment]
I guess calling them 'tags' instead of 'classes' might be more appropriate.

**Comment by robertvanhoesel** [comment]
@keiras I made a first change in [`4688d59` (#2)](https://github.com/aoe4world/data/pull/2/commits/4688d5930066f50ad90c94396686f3ef542acb7d) also added some types for structures, research and upgrades. Curious about your thoughts on these.
