### ISSUE TITLE
attack speed increase equation issue

### ISSUE THREAD

**Issue by acstanton515** [aoe4world/data#20]
I do not agree with this calculation

```
const increaseAttackSpeedByPercent = (speed: number, percent: number) => speed * round(1 - 1 / (1 - toPercent(percent)));
```

this results in things like composite-bows saying to multiply attack speed by 0.5

in explorer, this results in

ATTACK SPEED
1.625 --> 0.813S

In game, it is not reduced this much...

I think below might be more what you meant to implement:

```
const increaseAttackSpeedByPercentNew = (percent: number) => round(1/(1+percent/100));
```

I have used this new equation in the pull request and would be happy to merge it into yours.

**Comment by robertvanhoesel** [comment]
Hey! Fine with me if it actually reflects the game better. However, attack speed calculations have always been kind of sus in the game because not always it is properly calculated to what's reflected with the tooltip. The problem is in ambiguity in descriptions as well. 'Reduce the reload time of Archers by -33%." was the previous description. This is the formula as discussed with the devs and was/is/should be correct for most implementations, afaik. 

Feel free to move ahead but be sure to verify if all work as expected.

**Comment by acstanton515** [comment]
increaseAttackSpeedByPercent wasnt used for all attack speed  techs, but most of them.  I tested several of them and I really believe it is not accurate.  I do agree about sus UI and sus mechanics going on here (I'm honing in on ghulam), but I think a simple inversion calculation will be more accurate to game UI and actual game mechanic.  Happy to post a video here for evidence.
